services:
  - type: web
    name: delta-headlines-ai
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
